sudo: required

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required

script: bash ./test_db.sh


before_install:
  - wget https://raw.githubusercontent.com/Vincit/travis-oracledb-xe/master/accept_the_license_agreement_for_oracledb_xe_11g_and_install.sh
  - bash ./install.sh
